# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI do projeto de API Catalog Admin - FC3

on:
  push:
    branches: [ "main", "dev/ci" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: fc3-api-catalogo-de-videos-c-sharp

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read
      checks: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Start containers
      run: docker-compose -f "tests/FC.Codeflix.Catalog.IntegrationTests/docker-compose.yml" up -d --build
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --filter FullyQualifiedName\!~E2ETests

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Report Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true

  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Set BUILD_TAG
      run: |
          echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV
    
    - name: Print BUILD_TAG defined
      run: |
          echo "Branch     ---> ${{ github.head_ref || github.ref_name }}"
          echo "Run number ---> ${{ github.run_number }}"
          echo "Tag        ---> ${{ env.BUILD_TAG }}"

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        file: ./src/FC.Codeflix.Catalog.Api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USER}}/${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }},${{ secrets.DOCKER_HUB_USER}}/${{ env.IMAGE_NAME }}:latest
